### PR TITLE
Initial code for the integration test.

### PR DESCRIPTION
**Pull request by m12i**
This PR configures the integration test.
The next PR will have actual tests in it.

---
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26)

### CODE REVIEW

**Comment by danieljy** [comment]
Given I have no experience with the pom build system, I can't effectively review that file, at least not quickly.

If you think the integration test is generally applicable enough to go into OTP's codebase eventually, then this is fine. However if it's really just for us, I can imagine a lot less setup if you just have it run manually via a script both locally and in circle.

---

Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, all discussions resolved.

---

*[src/integration-test/java/org/opentripplanner/integrationtest/ITEndToEndTest.java, line 32 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCnpGTCEJRLw7en7z_6:-LCnpGTCEJRLw7en7z_7:b-4yr6dt) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/3d502e9f2c0246fabb25f63d74a9509b0c688847/src/integration-test/java/org/opentripplanner/integrationtest/ITEndToEndTest.java#L32)):*
> ```Java
>         }
>     }
> }
> ```

newline

---

*[src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java, line 28 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCnpN4T4A2BahCKvTIo:-LCnpN4T4A2BahCKvTIp:bvdm7eb) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/3d502e9f2c0246fabb25f63d74a9509b0c688847/src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java#L28)):*
> ```Java
> 
>         request.setHeader("Accept",
>                 "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
> ```

I think you should test against the JSON version of the response, rather than the XML one.

Accept: application/json should work:

https://github.com/sidewalklabs/parking/blob/master/api-routing/otp/client.go#L78

---

*[src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java, line 44 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCnqMfz7toC-ulEpGBM:-LCnqMfz7toC-ulEpGBN:b-swfd07) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/3d502e9f2c0246fabb25f63d74a9509b0c688847/src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java#L44)):*
> ```Java
>         while ((line = rd.readLine()) != null) {
>             result.append(line);
>         }
> ```

`String data = EntityUtils.toString(response.getEntity()); `

That seems a lot easier than doing all of this

---

*[src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java, line 49 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCnqQ01Ax4Vt3iG4bHV:-LCnqQ01Ax4Vt3iG4bHW:buj0pgm) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/3d502e9f2c0246fabb25f63d74a9509b0c688847/src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java#L49)):*
> ```Java
>     }
> 
>     public static String format(String xml, Boolean ommitXmlDeclaration) throws IOException, SAXException, ParserConfigurationException {
> ```

use JSON

---

*[src/integration-test/resources/graphs/router-config.json, line 7 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCnqo_P7qfQnP2vwCGR:-LCnqo_P7qfQnP2vwCGS:b-3y3mqa) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/3d502e9f2c0246fabb25f63d74a9509b0c688847/src/integration-test/resources/graphs/router-config.json#L7)):*
> ```JSON
>         "stairsReluctance": 4.0,
>         "carDropoffTime": 240
>     }
> ```

Will you be adding bikes in separately?

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-:-LCnqWcx3D29soQ2bHEj:b-gemywi)*

**Comment by m12i** [comment]
Yes, I made it so it can go into OTP's codebase. OTP would definitely benefit from having an integration test. 

---

Review status: 9 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/integration-test/java/org/opentripplanner/integrationtest/ITEndToEndTest.java, line 32 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCnpGTCEJRLw7en7z_6:-LCo4B4dA6erzn9lIqQW:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/3d502e9f2c0246fabb25f63d74a9509b0c688847/src/integration-test/java/org/opentripplanner/integrationtest/ITEndToEndTest.java#L32)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

newline
</blockquote></details>

Done.

---

*[src/integration-test/resources/graphs/router-config.json, line 7 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCnqo_P7qfQnP2vwCGR:-LCnuDoH5a1aiTwGezdy:b2nign6) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/3d502e9f2c0246fabb25f63d74a9509b0c688847/src/integration-test/resources/graphs/router-config.json#L7)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

Will you be adding bikes in separately?
</blockquote></details>

yes

---

*[src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java, line 28 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCnpN4T4A2BahCKvTIo:-LCo4CZ2-Iu9B6x6MBmU:b4g279y) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/3d502e9f2c0246fabb25f63d74a9509b0c688847/src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java#L28)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

I think you should test against the JSON version of the response, rather than the XML one.

Accept: application/json should work:

https://github.com/sidewalklabs/parking/blob/master/api-routing/otp/client.go#L78
</blockquote></details>

yes, good idea. Done.

---

*[src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java, line 44 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCnqMfz7toC-ulEpGBM:-LCnuBVhEyWIfSs-Q16S:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/3d502e9f2c0246fabb25f63d74a9509b0c688847/src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java#L44)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

`String data = EntityUtils.toString(response.getEntity()); `

That seems a lot easier than doing all of this


</blockquote></details>

Done.

---

*[src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java, line 49 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCnqQ01Ax4Vt3iG4bHV:-LCnuCUr4voyhvbVCP0p:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/3d502e9f2c0246fabb25f63d74a9509b0c688847/src/integration-test/java/org/opentripplanner/integrationtest/OtpHttpClient.java#L49)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

use JSON
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-:-LCo3_UZ1ZNpxiLKFAFJ:bcivl0f)*

**Comment by danieljy** [comment]
:lgtm:

Just fix test.

---

Reviewed 1 of 8 files at r2.
Review status: 10 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/integration-test/resources/test-data/test-config.json, line 2 at r2](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCoX9s1CrRyV4aN_Rqp:-LCoX9s2CLUgmcaGrYxP:b21qxid) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fd29bd46b2c72918616bac619444ee42fc2011a5/src/integration-test/resources/test-data/test-config.json#L2)):*
> ```JSON
> [
>   {
> ```

I would have just put this in the test itself. but it's fine.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-:-LCoXE7xBvd5Aa8nrYXr:bwzgyku)*

**Comment by m12i** [comment]
Review status: 9 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/integration-test/resources/test-data/test-config.json, line 2 at r2](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26#-LCoX9s1CrRyV4aN_Rqp:-LCofBjl8SGXFuh8Oi6W:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fd29bd46b2c72918616bac619444ee42fc2011a5/src/integration-test/resources/test-data/test-config.json#L2)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

I would have just put this in the test itself. but it's fine.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/26)*

**Pull request merged**
