### PR TITLE
[router, OTP]: Make BikeRentalUpdater use the default graph index

### PR DESCRIPTION
**Pull request by m12i**
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/15)

### CODE REVIEW

**Comment by m12i** [comment]
write operation are not synchronized in `HashGridSpatialIndex`, it must be taken care by the client. Read-only operation are multi-thread-safe though.

So we use synchronize when writing to idx. 

---

Review status: 7 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java, line 103 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/15#-LBv4h1433KNjBESBhWq:-LBvH1ha536O6JvzIqpI:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/8aebd538739c3ef2921d9cafb2ca3be66283c5cc/src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java#L103)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

Good question - probably another vestige of the fact that this router was based on transit.
</blockquote></details>

Done.

---

*[src/main/java/org/opentripplanner/updater/bike_park/BikeParkUpdater.java, line 101 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/15#-LBv5exX34ij3RhB6f8-:-LBvDiVC2sIfLkPm3Vca:by48ej2) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/8aebd538739c3ef2921d9cafb2ca3be66283c5cc/src/main/java/org/opentripplanner/updater/bike_park/BikeParkUpdater.java#L101)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

Should this also be changed eventually? Does this need a TODO or a note?
</blockquote></details>

changed it. 

---

*[src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java, line 59 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/15#-LBv5lxyCFlVPUeM58vs:-LBvGRgZ18fYqKB-I1wO:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/8aebd538739c3ef2921d9cafb2ca3be66283c5cc/src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java#L59)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

can you call this `splitter`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/15#-:-LBvGU6w71LP_2t_THsd:b-75abov)*

**Comment by danieljy** [comment]
Review status: 7 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java, line 106 at r2](https://reviewable.io/reviews/sidewalklabs/opentripplanner/15#-LBvJeQV9gcgtPrzaK0J:-LBvJeQV9gcgtPrzaK0K:b-9dttjb) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/42f66e1c95ec27bf95fec4c2d5d1227213e77004/src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java#L106)):*
> ```Java
>         if (hashGridSpatialIndex == null) {
>             // build a nice private spatial index, since we're adding and removing edges
>             synchronized (idx) {
> ```

remove this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/15)*

**Comment by m12i** [comment]
Review status: 7 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java, line 106 at r2](https://reviewable.io/reviews/sidewalklabs/opentripplanner/15#-LBvJeQV9gcgtPrzaK0J:-LBvL9L55ouN-RDU4trs:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/42f66e1c95ec27bf95fec4c2d5d1227213e77004/src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java#L106)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

remove this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/15)*

**Comment by danieljy** [comment]
:lgtm:

---

Review status: 7 of 11 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/15#-:-LBvMn9VBLimEYw-srjs:bnfp4nl)*

**Comment by danieljy** [comment]
Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/15)*

**Pull request merged**
