### PR TITLE
Cap-1612: Add Rental Bike Service Area

### PR DESCRIPTION
**Pull request by m12i**
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32)

### CODE REVIEW

**Comment by danieljy** [comment]
Review status: 26 of 27 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/main/java/org/opentripplanner/routing/core/State.java, line 281 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh6z70258eEK_cpNz9:-LDh6z70258eEK_cpNzA:bg355tx) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/core/State.java#L281)):*
> ```Java
>      */
>     public boolean isFloatingBikeDropOffAllowed() {
>         String bikeNetwork = stateData.bikeRentalNetworks != null ? stateData.bikeRentalNetworks.iterator().next() : null;
> ```

I'm confused as to why stateData has an array for bikeRentalNetworks - shouldn't it just have one? You're taking the first.

---

*[src/main/java/org/opentripplanner/routing/core/State.java, line 290 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh6nC4BnW1CXfezANB:-LDh6nC4BnW1CXfezANC:b-vq5iob) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/core/State.java#L290)):*
> ```Java
>             return false;
>         }
>         return bikeService.getBikeRentalRegions().get(bikeNetwork) == null ||
> ```

Separate into two booleans

`noRegionForNetwork`
`backEdgeInsideNetwork`

---

*[src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java, line 37 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh7EthDDfCbVIOHYMA:-LDh7EthDDfCbVIOHYMB:b9qugsv) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java#L37)):*
> ```Java
> import java.io.IOException;
> import java.io.ObjectOutputStream;
> import java.util.*;
> ```

Some styles say not to do this (I believe Google's for example).

---

*[src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java, line 913 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh7X5YB7NQRrNGIpZI:-LDh7X5YB7NQRrNGIpZJ:b-o6rq) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java#L913)):*
> ```Java
>         if (bikeNetworks == null){
>             // Note: bikeNetworks is not a threadsafe collection. This is not an issue as long as bikeNetworks is
>             // being written once (in OTP initialization time) and after that it's used only for reading.
> ```

Isn't this a problem if more than Coord adds regions?

---

*[src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java, line 88 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh92NF8OIgp6xFEUtR:-LDh8dPX0OpGX6vmD_CZ:b19gimk) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java#L88)):*
> ```Java
>     /**
>      *
>      * @return true if the link connects a street vertex to a transit stop, false otherwise.
> ```

false if it's the reverse (transit to street)


right?

---

*[src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java, line 120 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh8JhL8bz6gkw4ba8W:-LDh8JhL8bz6gkw4ba8X:bu1zkk3) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java#L120)):*
> ```Java
>         StateEditor s1 = s0.edit(this);
> 
>         // Forbid taking a rented bike on any transit.
> ```

Update the comments here.

---

*[src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java, line 128 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh9HEd0FGTfinv2ir7:-LDh9HEd0FGTfinv2ir8:b-4j09q1) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java#L128)):*
> ```Java
>                 // TODO(mahmood): add `incrementWeight` and `incrementTimeInSeconds` as cost of drop off
>                 s1.setBikeRenting(false, false);
>                 s1.setBikeRentalNetwork(new HashSet<>());
> ```

I still don't understand why you need multiple bike networks

---

*[src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java, line 153 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDhA5hI39C7wYM2ah3-:-LDhA5hJ6eQiOff5ccvg:b-eu7a30) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java#L153)):*
> ```Java
>         // Create graph writer runnable to apply bike network service regions to the graph
>         if (regions != null && !regions.isEmpty()) {
>             updaterManager.execute(new BikeRentalRegionGraphWriterRunnable(regions));
> ```

This will run in parallel with other updates so you do need to make sure that updating code is thread safe I think.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java, line 285 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDhBFD8-blweO0CzPhK:-LDhBFD8-blweO0CzPhL:b-ssgbqm) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java#L285)):*
> ```Java
>                 if (coversFrom && coversTo) {
>                     edge.addBikeNetwork(region.network);
>                 } else if (coversFrom ^ coversTo) {
> ```

this really could just be `||` since you cover the `&&` above.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java, line 311 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDhCRDHCsdRcN8kigYC:-LDhCRDHCsdRcN8kigYD:b-o7qxl) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java#L311)):*
> ```Java
>                 Geometry intersectionLineString = intersectionLineStrings.getGeometryN(i);
>                 for (Coordinate coordinate : intersectionLineString.getCoordinates()) {
>                     if (coordinate.equals(equals(from.getCoordinate())) ||
> ```

maybe just comment on what you expect and why you ignore.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 23 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh4Ymc4t9n0msEoG3_:-LDh4Ymc4t9n0msEoG3a:bnq8y3l) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L23)):*
> ```Java
>     private static final Logger LOG = LoggerFactory.getLogger(CoordBikeRentalDataSource.class);
> 
>     private static final ObjectMapper deserializer = new ObjectMapper();
> ```

jsonDeserializer? 

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 108 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh5iIA5kDsbXms8xNt:-LDh5iIA5kDsbXms8xNu:b-q582p) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L108)):*
> ```Java
>             return updateBikeStations();
>         } else {
>             isRegionsUpdated = true;
> ```

if this fails the first time, it will never try again

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 208 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDhSa5G02akhcXPQD_P:-LDh3rdf3vjwJ4Hawbxx:bgqaxyh) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L208)):*
> ```Java
>     }
> 
>     class CoordBikeRegionDataSource extends GenericJsonBikeRentalDataSource<BikeRentalRegion> {
> ```

It seems funny to be calling GenericJsonBikeRentalDataSource here and 

---

*[src/test/java/org/opentripplanner/common/geometry/GeometryUtilsTest.java, line 16 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh2jyZ-VW8vCHqH1oZ:-LDh2jyZ-VW8vCHqH1o_:b-4evhrf) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/test/java/org/opentripplanner/common/geometry/GeometryUtilsTest.java#L16)):*
> ```Java
> package org.opentripplanner.common.geometry;
> 
> import com.vividsolutions.jts.geom.*;
> ```

Rebase to remove this diff.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32)*

**Comment by m12i** [comment]
Review status: 2 of 20 files reviewed at latest revision, 14 unresolved discussions.

---

*[src/main/java/org/opentripplanner/routing/core/State.java, line 281 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh6z70258eEK_cpNz9:-LDhuC6jB0Ly51zcarN0:ba4rz7x) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/core/State.java#L281)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

I'm confused as to why stateData has an array for bikeRentalNetworks - shouldn't it just have one? You're taking the first.
</blockquote></details>

I think they want to model the possibility picking up bikes from different networks. So when dropping off, if one of those matches, you can drop off. 

---

*[src/main/java/org/opentripplanner/routing/core/State.java, line 290 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh6nC4BnW1CXfezANB:-LDhwdWRDjftLDYPwDfG:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/core/State.java#L290)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

Separate into two booleans

`noRegionForNetwork`
`backEdgeInsideNetwork`
</blockquote></details>

Done.

---

*[src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java, line 37 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh7EthDDfCbVIOHYMA:-LDhxMUt3pfAyLjnftwv:b-6nau4j) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java#L37)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

Some styles say not to do this (I believe Google's for example).
</blockquote></details>

Done. My IDE does it automatically. I turned it off.

---

*[src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java, line 913 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh7X5YB7NQRrNGIpZI:-LDhxhtiCx1z_-FLfuAA:b-6goybf) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java#L913)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

Isn't this a problem if more than Coord adds regions?
</blockquote></details>

There is no concurrency in loading time. So as long as multiple sources add regions in loading time (which is not concurrently), it's fine. 

---

*[src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java, line 88 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh92NF8OIgp6xFEUtR:-LDhyHxv7mvLSJek6SAL:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java#L88)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

false if it's the reverse (transit to street)


right?
</blockquote></details>

Done.

---

*[src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java, line 120 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh8JhL8bz6gkw4ba8W:-LDhz6kq2PbLq4xP1XAz:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java#L120)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

Update the comments here.
</blockquote></details>

Done.

---

*[src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java, line 128 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh9HEd0FGTfinv2ir7:-LDhzB6533ACSAFK0QEa:b4w0so5) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java#L128)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

I still don't understand why you need multiple bike networks
</blockquote></details>

This is the original OTP design and as I explained above, they want to carry as many bike as you can pick off from one location.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java, line 153 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDhA5hI39C7wYM2ah3-:-LDi15sU3LTlauzrUQ2D:bhbuo12) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java#L153)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

This will run in parallel with other updates so you do need to make sure that updating code is thread safe I think.
</blockquote></details>

this will iterate on regions and create bike drop offs. what do you mean by `updating code`?

---

*[src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java, line 285 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDhBFD8-blweO0CzPhK:-LDhzfeG9lJC4oO6A4Lq:b-e8513l) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java#L285)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

this really could just be `||` since you cover the `&&` above.
</blockquote></details>

good point!

---

*[src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java, line 311 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDhCRDHCsdRcN8kigYC:-LDi-deI14P9ali6v2C8:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java#L311)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

maybe just comment on what you expect and why you ignore.
</blockquote></details>

Done.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 23 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh4Ymc4t9n0msEoG3_:-LDi0973DIVAwK4QawdC:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L23)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

jsonDeserializer? 
</blockquote></details>

Done.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 108 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh5iIA5kDsbXms8xNt:-LDi0Th0-tf0PRp0VyRY:b-5n9fuo) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L108)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

if this fails the first time, it will never try again
</blockquote></details>

right. fixed it

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 208 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDhSa5G02akhcXPQD_P:-LDi0XYL3VaWxOObh24V:b-7ql1td) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L208)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

It seems funny to be calling GenericJsonBikeRentalDataSource here and 
</blockquote></details>

fixed

---

*[src/test/java/org/opentripplanner/common/geometry/GeometryUtilsTest.java, line 16 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh2jyZ-VW8vCHqH1oZ:-LDi0d7a4FbS1HUQQgal:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/test/java/org/opentripplanner/common/geometry/GeometryUtilsTest.java#L16)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

Rebase to remove this diff.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32)*

**Comment by m12i** [comment]
Review status: 14 of 33 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/main/java/org/opentripplanner/routing/core/State.java, line 281 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh6z70258eEK_cpNz9:-LDrTbT1AGuC-8Fqsrzg:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/core/State.java#L281)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

Note.
</blockquote></details>

Done.

---

*[src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java, line 913 at r1](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDh7X5YB7NQRrNGIpZI:-LDlqyYd6wSwjd3ZDGNi:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/47faaa31e9104df12911106bbc052400506dcce6/src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java#L913)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

address this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32)*

**Comment by danieljy** [comment]
:lgtm:

So the fundamental change was fixing the race condition between the two updaters, right? 

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java, line 154 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDrc-HgCVEl3lI2lVw0:-LDrc-HgCVEl3lI2lVw1:b-8k46un) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java#L154)):*
> ```Java
>         List<BikeRentalRegion> regions = source.getRegions();
> 
>         // Filter out the regions that are already applied.
> ```

So fundamentally, it's a bit awkward that regions are treated like stations, since they don't change - we poll every minute, but discard the regions if they were processed already.

TODO for what happens if regions change .

Shouldn't the BikeRentalGraphWrite be the one that manages what to ignore and what to update?

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 72 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDrb-ca2WLzbdx_8VKN:-LDrb-ca2WLzbdx_8VKO:b-9dttjb) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L72)):*
> ```Java
>         List<BikeRentalStation> stations = new ArrayList<>();
>         stationSources.forEach(s -> stations.addAll(s.getStations()));
> //        stationSources.forEach(s -> stations.addAll(s.getStations().stream().filter(r-> !r.networks.contains("CapitalBikeShare")).collect(Collectors.toList())));
> ```

remove this.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 80 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDrbAyb4-tF6ueie26B:-LDrbAyb4-tF6ueie26C:ba5wo3j) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L80)):*
> ```Java
>     public List<BikeRentalRegion> getRegions() {
>         Map<String, BikeRentalRegion> regions = new HashMap<>();
>         regionSources.forEach(s -> s.getRegions().forEach(r -> regions.put(r.network, r)));
> ```

so functional!

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 82 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDrbCgM4-CytBmP4s-B:-LDrbCgM4-CytBmP4s-C:bepf6kg) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L82)):*
> ```Java
>         regionSources.forEach(s -> s.getRegions().forEach(r -> regions.put(r.network, r)));
> 
>         if(regions.containsKey("JumpDC")) {
> ```

space after if

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 232 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDraH5g6FoO6TsypI1A:-LDraH5g6FoO6TsypI1B:b-qsyuya) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L232)):*
> ```Java
>         public BikeRentalRegion makeRegion(JsonNode jsonNode) {
>             JsonNode properties = jsonNode.path("properties");
>             String stationType = properties.get("station_type").asText();
> ```

final?

---

*[src/main/java/org/opentripplanner/updater/bike_rental/GenericJsonBikeRentalDataSource.java, line 130 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDr_dk1CZ8zLMZsZJpv:-LDr_dk1CZ8zLMZsZJpw:b-t90i39) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/GenericJsonBikeRentalDataSource.java#L130)):*
> ```Java
>                     out.add(item);
>             }
>         } else {
> ```

So if it's not an array, you assume it's one Item - just make a note of that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-:-LDrcX9y7TPtW80ryTjK:b-dc26qg)*

**Comment by m12i** [comment]
yes!

---

Review status: 25 of 33 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java, line 154 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDrc-HgCVEl3lI2lVw0:-LDrir4T4bykwpmaBU_c:btkel2z) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java#L154)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

So fundamentally, it's a bit awkward that regions are treated like stations, since they don't change - we poll every minute, but discard the regions if they were processed already.

TODO for what happens if regions change .

Shouldn't the BikeRentalGraphWrite be the one that manages what to ignore and what to update?
</blockquote></details>

regions change less often. For now the benefit is that if we add a new bike system in a city, OTP will pick up both their stations and their region
In future, one can further develop the region and check if its geometry has changed then remove all the boarder drop offs and add new ones.  This way it will support on the fly change in region geometry (which may happen more frequent than what we think)


`BikeRentalGraphWriterRunnable` cannot manage them, since its object is created every time we call update. BikeRentalUpdater is the one, as only one instance of it will be created for, say Coord updater and lives as long as OTP is running.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 72 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDrb-ca2WLzbdx_8VKN:-LDrhRjt8r6EfUteHqdw:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L72)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

remove this.
</blockquote></details>

Done.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 80 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDrbAyb4-tF6ueie26B:-LDrhVaz83zFVIonk8AJ:bwyw6w2) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L80)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

so functional!
</blockquote></details>

Java 8!

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 82 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDrbCgM4-CytBmP4s-B:-LDrhap76dkqokP7nUSY:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L82)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

space after if
</blockquote></details>

Done.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java, line 232 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDraH5g6FoO6TsypI1A:-LDriOfF44y1bZrloJgs:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/CoordBikeRentalDataSource.java#L232)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

final?
</blockquote></details>

Done.

---

*[src/main/java/org/opentripplanner/updater/bike_rental/GenericJsonBikeRentalDataSource.java, line 130 at r3](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-LDr_dk1CZ8zLMZsZJpv:-LDriniP1Ixte4ez1gY-:b-896fix) ([raw file](https://github.com/sidewalklabs/opentripplanner/blob/fdc2f02d1d8f11142ae4b1ec6fe2c4d09a98ac93/src/main/java/org/opentripplanner/updater/bike_rental/GenericJsonBikeRentalDataSource.java#L130)):*
<details><summary><i>Previously, danieljy (Daniel Yehuda) wrote…</i></summary><blockquote>

So if it's not an array, you assume it's one Item - just make a note of that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sidewalklabs/opentripplanner/32#-:-LDrh76P4msQxDYsq3xU:b-7g7nw5)*

**Pull request merged**
